cfoch/SIGAD-business

pom.xml
src/main/java/com/sigad/sigad/business/CapacidadTienda.java
src/main/java/com/sigad/sigad/business/ClienteDireccion.java
src/main/java/com/sigad/sigad/business/ClienteFecha.java
src/main/java/com/sigad/sigad/business/Constante.java
src/main/java/com/sigad/sigad/business/DetalleOrdenCompra.java
src/main/java/com/sigad/sigad/business/Insumo.java
src/main/java/com/sigad/sigad/business/Locacion.java
src/main/java/com/sigad/sigad/business/LoteInsumo.java
src/main/java/com/sigad/sigad/business/LoteTienda.java
src/main/java/com/sigad/sigad/business/OrdenCompra.java
src/main/java/com/sigad/sigad/business/Perfil.java
src/main/java/com/sigad/sigad/business/Producto.java
src/main/java/com/sigad/sigad/business/ProductoCategoria.java
src/main/java/com/sigad/sigad/business/ProductoFragilidad.java
src/main/java/com/sigad/sigad/business/ProductoPrecio.java
src/main/java/com/sigad/sigad/business/Proveedor.java
src/main/java/com/sigad/sigad/business/SIGADBusinessMain.java
src/main/java/com/sigad/sigad/business/Tienda.java
src/main/java/com/sigad/sigad/business/TipoPago.java
src/main/java/com/sigad/sigad/business/Usuario.java
src/main/java/com/sigad/sigad/business/Vehiculo.java
src/main/java/com/sigad/sigad/business/ids/CapacidadTiendaId.java
src/main/java/com/sigad/sigad/business/ids/LoteTiendaId.java
src/main/resources/hibernate.cfg.xml

modelos: Agregar estructura base

---

.gitignore
src/main/java/com/sigad/sigad/business/ClienteDireccion.java
src/main/java/com/sigad/sigad/business/DetallePedido.java
src/main/java/com/sigad/sigad/business/DetalleReparto.java
src/main/java/com/sigad/sigad/business/EstadoPedido.java
src/main/java/com/sigad/sigad/business/Insumo.java
src/main/java/com/sigad/sigad/business/Pedido.java
src/main/java/com/sigad/sigad/business/PedidoEstado.java
src/main/java/com/sigad/sigad/business/Producto.java
src/main/java/com/sigad/sigad/business/ProductoDescuento.java
src/main/java/com/sigad/sigad/business/ProductoInsumo.java
src/main/java/com/sigad/sigad/business/Reparto.java
src/main/java/com/sigad/sigad/business/Usuario.java
src/main/resources/hibernate.cfg.xml

https://github.com/cfoch/SIGAD-business/issues/3
This closes #3

modelos: Agregar modelos faltantes entre otras modificaciones menores

---

src/main/java/com/sigad/sigad/app/controller/HomeController.java

ui: home: Corregir caída del programa al iniciar sesión

---

src/main/java/com/sigad/sigad/app/controller/HomeController.java

ui: home: Reducir botones para que encajen en pantalla

---

src/main/java/com/sigad/sigad/app/controller/HomeController.java
src/main/java/com/sigad/sigad/app/controller/LoginController.java
src/main/java/com/sigad/sigad/personal/controller/PersonalController.java

logout and personal popup changed

---

src/main/java/com/sigad/sigad/business/Proveedor.java
src/main/java/com/sigad/sigad/business/ProveedorInsumo.java
src/main/java/com/sigad/sigad/deposito/helper/DepositoHelper.java
src/main/java/com/sigad/sigad/helpers/cargaMasiva/CargaMasivaHelper.java
src/main/resources/hibernate.cfg.xml

Actualizacion de modelos

---

pom.xml
src/main/java/com/sigad/sigad/business/helpers/GMapsHelper.java

helpers: Agregar utilidades para Google API"

---

src/main/java/com/sigad/sigad/business/Producto.java
src/main/java/com/sigad/sigad/business/Usuario.java

this closes #55 
this closes #54

Agregar modelos para soportar productos favoritos

---

src/main/java/com/sigad/sigad/business/ClienteDescuento.java
src/main/java/com/sigad/sigad/business/ComboPromocion.java
src/main/java/com/sigad/sigad/business/DetallePedido.java
src/main/java/com/sigad/sigad/business/Pedido.java
src/main/java/com/sigad/sigad/business/Perfil.java
src/main/java/com/sigad/sigad/business/Producto.java
src/main/java/com/sigad/sigad/business/ProductoDescuento.java
src/main/java/com/sigad/sigad/business/ProductosCombos.java
src/main/java/com/sigad/sigad/business/Usuario.java
src/main/resources/hibernate.cfg.xml

Agregar relaciones de descuentos

---

src/main/java/com/sigad/sigad/helpers/cargaMasiva/CargaMasivaHelper.java

carga masiva: Asignar tipo de vehículo al cargar vehículo

---

.gitignore
src/main/java/com/sigad/sigad/pedido/controller/DatosPedidoController.java

pedidos: Corregir error de no poder guardar pedido

---

.gitignore
.gitmodules
src/main/java/com/sigad/sigad/pedido/controller/SeleccionarProductosController.java

Guardar coordenada Y

---

pom.xml
src/main/java/com/sigad/sigad/business/helpers/GMapsHelper.java
src/main/java/com/sigad/sigad/pedido/controller/SolicitarDireccionController.java
src/main/resources/com/sigad/sigad/pedido/view/solicitarDireccion.fxml

ui: ventas: Mostrar mapa para escoger dirección

---

src/main/java/com/sigad/sigad/business/Constantes.java

Constantes actualizado

---

src/main/java/com/sigad/sigad/business/helpers/MigracionPedidosHelper.java

carga masiva: Generar pedidos con coordenadas geográficas

---

src/main/java/com/sigad/sigad/business/helpers/MigracionPedidosHelper.java

carga masiva: Generar pedidos con fecha de entrega esperada

---

src/main/java/com/sigad/sigad/business/ProductoDescuento.java
src/main/java/com/sigad/sigad/business/helpers/ProductoDescuentoHelper.java
src/main/java/com/sigad/sigad/descuentos/controller/RegistrarDescuentoProductoController.java
src/main/java/com/sigad/sigad/helpers/cargaMasiva/CargaMasivaHelper.java

Ya no acepta stock maximo, al menos en back, ni en base de datos
This closes #174

Editar modelo de descuentos Productos

---

src/main/java/com/sigad/sigad/app/repartos/controller/RepartoMapaController.java
src/main/java/com/sigad/sigad/business/helpers/PedidoHelper.java

ui: repartos: grupo repartos: Mostrar icono diferente por estado

---

src/main/java/com/sigad/sigad/business/helpers/AlgoritmoHelper.java

algoritmo: Asignar repartidor a reparto

---

src/main/java/com/sigad/sigad/business/helpers/BaseHelper.java

helpers: base: Cambiar modo de acceso de método init

---

src/main/java/com/sigad/sigad/productos/controller/ProductosIndexController.java
src/main/java/com/sigad/sigad/productos/controller/ProductosManagementController.java
src/main/resources/com/sigad/sigad/productos/view/ProductosManagement.fxml

Products view

---

src/main/java/com/sigad/sigad/business/Pedido.java
src/main/java/com/sigad/sigad/pedido/controller/SeleccionarProductosController.java

Editar pedido bug

---

pom.xml

Se agrega configuración para que luego de compilar se obtenga un jar ejecutable

JAR Ejecutable (sin dependencias)

---

src/main/java/com/sigad/sigad/business/ComboPromocion.java
src/main/java/com/sigad/sigad/business/helpers/ComboPromocionHelper.java
src/main/java/com/sigad/sigad/descuentos/controller/MantenimientoDescuentosController.java
src/main/java/com/sigad/sigad/descuentos/controller/RegistrarComboProductosController.java
src/main/java/com/sigad/sigad/descuentos/controller/RegistrarDescuentoCategoriaProductoController.java
src/main/java/com/sigad/sigad/descuentos/controller/RegistrarDescuentoClientesController.java
src/main/java/com/sigad/sigad/descuentos/controller/RegistrarDescuentoProductoController.java
src/main/java/com/sigad/sigad/pedido/controller/SeleccionarProductosController.java
src/main/resources/com/sigad/sigad/descuentos/view/RegistrarComboProductos.fxml

Fix bug al crear combo, fix ver descuentos

---

src/main/java/com/sigad/sigad/pedido/controller/DevolucionPedidoController.java
src/main/java/com/sigad/sigad/pedido/controller/MantenimientoPedidosController.java

Pantalla devolucion

---

src/main/java/com/sigad/sigad/business/helpers/AlgoritmoHelper.java

ui: repartidores: dialogo: Agregar mensajes de error al generar rutas

---

src/main/java/com/sigad/sigad/pedido/controller/DatosPedidoController.java

Los pedidos considerados para el descuento de usuario 

---

src/main/java/com/sigad/sigad/business/helpers/DBPopulationHelper.java
src/main/java/com/sigad/sigad/business/helpers/MigracionPedidosHelper.java
src/main/java/com/sigad/sigad/pedido/controller/DatosPedidoController.java

Generar 30 pedidos

---

src/main/java/com/sigad/sigad/business/helpers/DBPopulationHelper.java
src/main/java/com/sigad/sigad/business/helpers/MigracionPedidosHelper.java
src/main/java/com/sigad/sigad/pedido/controller/DatosPedidoController.java
src/main/java/com/sigad/sigad/pedido/controller/EditarEliminarPedidoController.java
src/main/java/com/sigad/sigad/pedido/controller/MantenimientoPedidosController.java
src/main/resources/com/sigad/sigad/pedido/view/EditarEliminarPedido.fxml

Igv en total de pedidos
